CREATE TABLE Nodes(id INTEGER PRIMARY KEY AUTOINCREMENT, classname VARCHAR(25), name VARCHAR(25), isTransient SMALLINT UNSIGNED DEFAULT 0, isQuarantined SMALLINT UNSIGNED DEFAULT 0 , isAvailable SMALLINT UNSIGNED DEFAULT 1);
CREATE TABLE Sessions(id INTEGER PRIMARY KEY AUTOINCREMENT, username VARCHAR(25), name VARCHAR(25));
CREATE TABLE Plans(id INTEGER PRIMARY KEY AUTOINCREMENT, session_id INT, node_id INT, namepackage VARCHAR(25), versionpackage VARCHAR(25), packagetype VARCHAR(25));

CREATE TABLE NodesAttributes(id INTEGER PRIMARY KEY AUTOINCREMENT, key VARCHAR(25), value VARCHAR(25), node_id INT);