SSH_PATH = "{0}.ssh/"
TESTGRID_KEY_NAME = "testGridkey"
SSH_PATH_SFTP = ".ssh/"
AUTHORIZED_KEYS = "authorized_keys"
NEW_USER = "testUser"
SSH_CONFIG_CONTENT = "StrictHostKeyChecking no\n"
SSH_CONFIG = "config"
