#!/bin/sh

set -e -x


adduser --system --disabled-login --disabled-password --gecos "" tgc

if [ -f "/home/tgc/.ssh/id_rsa.pub" ];
then
   echo "ssh key exist"
else
   echo "ssh key generation"
   sudo -u tgc ssh-keygen -t rsa -f /home/tgc/.ssh/id_rsa -q -N ""
fi
service tgc restart